name: Run Pytest and Codecov with Hatch

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: olympus
    environment: manual-approval
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build --target hatch -t myapp:hatch .
    - name: Run pytest and generate coverage report
      run: docker run --rm -e HATCH_ENV=test -v "${{ github.workspace }}:/app" myapp:hatch cov
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: ${{ github.workspace }}/.coverage
